export const Users = [
    {
      id:1,
      profilePicture: "https://w0.peakpx.com/wallpaper/816/168/HD-wallpaper-sasuke-uchiha-head-black-hair-anime-naruto-shippuuden-naruto.jpg",
      username: "Sasuke Uchiha",
    },
    {
      id:2,
      profilePicture: "https://i.redd.it/yfxbu80xnbt71.jpg",
      username: "Itachi Uchiha",
    },
    {
      id:3,
      profilePicture: "https://www.liveakhbar.in/wp-content/uploads/2022/09/Sanemi-Shinazugawa.jpg",
      username: "Sanemi Shinazugawa",
    },
    {
      id:4,
      profilePicture: "https://as01.epimg.net/meristation_en/imagenes/2022/04/21/news/1650502649_880140_1650503074_noticia_normal.jpg",
      username: "Naruto Uzumaki",
    },
    {
      id:5,
      profilePicture: "https://i.pinimg.com/736x/8f/e2/e4/8fe2e4e5ce6716e6fc63eb8709896bfe.jpg",
      username: "Madara Uchiha",
    },
    {
      id:6,
      profilePicture: "https://staticg.sportskeeda.com/editor/2022/01/d9670-16431849169972-1920.jpg",
      username: "Rengoku Kyojuro",
    },
    {
      id:7,
      profilePicture: "https://m.media-amazon.com/images/I/91w63Uky9SL._SY450_.jpg",
      username: "Tanjirou Kamado",
    },
    {
      id:8,
      profilePicture: "https://i1.sndcdn.com/avatars-si5mohNGXHKIGaVN-yJQm4Q-t500x500.jpg",
      username: "Nezuko Kamado",
    },
    {
      id:9,
      profilePicture: "https://qph.cf2.quoracdn.net/main-qimg-3bf9486712f07f8c0f608d56808ee39a-lq",
      username: "Yoriichi Tsugikuni",
    },
    {
      id:10,
      profilePicture: "https://staticg.sportskeeda.com/editor/2022/02/8c1f4-16448390860345-1920.jpg",
      username: "Uzui Tengen",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "assets/post/1.jpeg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "assets/post/2.jpeg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/post/3.jpeg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/post/4.jpeg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/post/5.jpeg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/post/6.jpeg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/post/7.jpeg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/post/8.jpeg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/post/9.jpeg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/post/10.jpeg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];